### ISSUE TITLE
Slow scrolling

### ISSUE THREAD

**Issue by efremidze** [BohdanOrlov/BouncyPageViewController#1]
Scrolling is very slow on my devices.

**Comment by efremidze** [comment]
Fixed it by adding scroll velocity. Also you should allow for customizing page size. I can make a PR.

**Comment by BohdanOrlov** [comment]
@efremidze I don't see how scroll velocity could help, could you make a PR?

**Comment by BohdanOrlov** [comment]
Apparently, I didn't find time for this, my fault 😇
Let me know if this is relevant for anyone, closing for now.
