### ISSUE TITLE
App crash when touching upper right corner.

### ISSUE THREAD

**Issue by lahirumm92** [BohdanOrlov/BouncyPageViewController#3]
I'm experiencing a **App crash** when i'm touching upper area. i'm using swift 4. latest Xcode.
[Screen Recording video.zip](https://github.com/BohdanOrlov/BouncyPageViewController/files/2196448/Screen.Recording.video.zip)

**Comment by BohdanOrlov** [comment]
Hey, @lahirumm92 sorry for the late reply.

Did you tap on the status bar?

**Comment by lahirumm92** [comment]
Yes i have. It happens when i tap on between status bar and middle of the screen. We have sent a video

**Comment by BohdanOrlov** [comment]
Fixed crash in 0.1.1, now tapping there does nothing.

**Comment by lahirumm92** [comment]
Hi, 
Thank you very much to fixed this problem
